apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.redisPort }}
      targetPort: redis
      protocol: TCP
    - name: cluster
      port: {{ .Values.service.clusterPort }}
      targetPort: cluster
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
