apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-config-pvc
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
