apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: console
      protocol: TCP
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
